# Generated by Django 3.2 on 2023-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(default='', max_length=50)),
                ('sr', models.CharField(default='', max_length=50)),
                ('person_id', models.CharField(default='', max_length=200)),
                ('Time', models.DateTimeField()),
                ('off_Time', models.DateTimeField()),
                ('ip', models.CharField(default='', max_length=200)),
                ('Activity', models.CharField(default='Tap Tyag MM', max_length=200)),
                ('First_Name', models.CharField(default='', max_length=200)),
                ('Husband_Father_Name', models.CharField(default='', max_length=200)),
                ('Surname', models.CharField(default='', max_length=200)),
                ('Srimad_dasvekalik_RegistrationID_1', models.CharField(default='', max_length=200)),
                ('Srimad_dasvekalik_RegistrationID_2', models.CharField(default='', max_length=200)),
                ('full_name', models.CharField(default='', max_length=200)),
                ('Age', models.IntegerField(default=0)),
                ('Country', models.CharField(default='', max_length=200)),
                ('Transalate', models.CharField(default='', max_length=200)),
                ('Pincode', models.CharField(max_length=10)),
                ('India_Whatsapp_No', models.CharField(max_length=30)),
                ('Foreign_WhatsappNo', models.CharField(blank=True, max_length=30)),
                ('Pincode_FR', models.CharField(blank=True, max_length=10)),
                ('Sub_Region', models.CharField(default='', max_length=200)),
                ('zila', models.CharField(default='', max_length=200)),
                ('State', models.CharField(default='', max_length=200)),
                ('Region', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('C1', models.CharField(default='', max_length=200)),
                ('C2', models.CharField(default='', max_length=200)),
                ('C3', models.CharField(default='', max_length=100)),
                ('C4', models.CharField(default='', max_length=100)),
                ('C5', models.CharField(default='', max_length=100)),
                ('C6', models.CharField(default='', max_length=100)),
                ('C10', models.CharField(default='', max_length=100)),
                ('A1', models.CharField(default='', max_length=100)),
                ('A2', models.CharField(default='', max_length=100)),
                ('A3', models.CharField(default='', max_length=100)),
                ('A4', models.CharField(default='', max_length=100)),
                ('A5', models.CharField(default='', max_length=100)),
                ('A6', models.CharField(default='', max_length=100)),
                ('A7', models.CharField(default='', max_length=100)),
                ('A8', models.CharField(default='', max_length=100)),
                ('A9', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='A10',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='A11',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='A12',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='A13',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='A14',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='C7',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='C8',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='C9',
        ),
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='score',
        ),
        migrations.AddField(
            model_name='table_swadhyay',
            name='C10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table_swadhyay',
            name='Srimad_dasvekalik_RegistrationID_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='table_swadhyay',
            name='Srimad_dasvekalik_RegistrationID_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='table_swadhyay',
            name='Transalate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='table_swadhyay',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='table_swadhyay',
            name='si',
            field=models.CharField(default='', max_length=50),
        ),
    ]
