# Generated by Django 3.2 on 2023-11-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231107_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_swadhyay',
            name='address',
        ),
    ]
