# Generated by Django 3.2 on 2023-11-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_table_swadhyay_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_swadhyay',
            name='Time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_swadhyay',
            name='off_Time',
            field=models.DateTimeField(blank=True),
        ),
    ]
